keys:
  - &users:
    - &real age14g5mwrz5z4ktyaqecd7vhtlkxje8v9yt3d273jg6rn39sxsuqd7s93nht9
  - &hosts:
    - &main age1jh260ysuz35ymlrn9ek96uu78ll67ms7f2rk7fw4wggtvu7h4u7st28hz7
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *real
      - *main